/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "events": {
        "test": string;
    };
    "admin": {
        "emails": {
            "register": {
                "subject": string;
                "body": {
                    "preview": string;
                    "cta-button": string;
                    "greetings": string;
                };
            };
        };
        "errors": {
            "last": {
                "user": string;
                "role": string;
            };
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
