query ManageGetUsers @blocking {
	users: getUsers(where: { registerToken: null }) {
		email
		firstName
		lastName
		roles {
			text
		}
		profilePictureRef
	}
	unregisteredUsers: getUsers(where: { registerToken: { not: null } }) {
		email
		firstName
		lastName
		roles {
			text
		}
		profilePictureRef
		registerToken
	}
}
