FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

# ====================

FROM base AS build

WORKDIR /app

COPY . .
COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma/

RUN --mount=type=cache,id=pnpm,target=$PNPM_HOME/store pnpm install --frozen-lockfile

ENV NODE_ENV=production
RUN pnpm run build

# ====================
 
FROM base AS dokploy

WORKDIR /app

ENV NODE_ENV=production
 
# Copy only the necessary files
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
 
EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]