name: CD - Client

on: workflow_dispatch

env:
  NODE_VERSION: '20'
  PNPM_VERSION: 8

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
      VERCEL_ORG_ID: '${{ vars.VERCEL_ORG_ID }}'
      VERCEL_PROJECT_ID: '${{ vars.VERCEL_PROJECT_ID }}'

    steps:
      - name: Check Vercel Token
        if: env.VERCEL_TOKEN == ''
        run: |
          echo 'You are missing the VERCEL_TOKEN secret!'
          exit 1

      - name: Check Vercel Org ID
        if: env.VERCEL_ORG_ID == ''
        run: |
          echo 'You are missing the VERCEL_ORG_ID secret!'
          exit 1

      - name: Check Vercel Project ID
        if: env.VERCEL_PROJECT_ID == ''
        run: |
          echo 'You are missing the VERCEL_PROJECT_ID secret!'
          exit 1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get git HEAD sha
        id: commit-vars
        run: |
          echo "git_head_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: pnpm install

      - name: Init
        run: pnpm run init --no-api

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        id: vercel-action
        with:
          vercel-token: '${{ secrets.VERCEL_TOKEN }}'
          vercel-org-id: '${{ vars.VERCEL_ORG_ID }}'
          vercel-project-id: '${{ vars.VERCEL_PROJECT_ID }}'
          vercel-args: '--prod'
          github-comment: false

      - name: Comment on deploy commit
        uses: peter-evans/commit-comment@v2
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          sha: '${{ steps.commit-vars.outputs.git_head_sha }}'
          body: |
            🤖 This commit is now deployed to Vercel!

            ## ${{ steps.vercel-action.outputs.preview-name }}

            ${{ steps.vercel-action.outputs.preview-url }}
