mutation CreateNewUser($email: String!, $firstName: String, $lastName: String, $roles: RoleCreateNestedManyWithoutUsersInput) {
	createUser(data: { email: $email, firstName: $firstName, lastName: $lastName, roles: $roles }) {
		email
		firstName
		lastName
	}
}
